services:

  front_service:
    image: front_service
    ports:
      - 5000:5000
    networks:
      - net

  auth_service:
    image: auth_service
    ports:
      - 5001:5001
    networks:
      - net

  feed_service:
    image: feed_service
    ports:
      - 5002:5002
    networks:
      - net

networks:
  net: { }