version: '2.0'
services:

  front_service:
    build: './frontend'
    image: frontend
    ports:
      - 5000:5000
    networks:
      - net

  auth_service:
    build: './backend'
    image: backend
    ports:
      - 5001:5001
    networks:
      - net

networks:
  net: