version: '2.0'

networks:
  DMZ:
    external: true
  BACK:
    external: true
  DATA:
    external: true

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    networks:
      DMZ:
        ipv4_address: 192.168.20.10

  backend:
    image: backend
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: annuaire
    networks:
      BACK:
        ipv4_address: 192.168.10.10


  db:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: annuaire
    volumes:
      - ./data:/var/lib/mysql #cheminlocal:cheminconteneur
#    networks:
#      DATA:
#        ipv4_address: 192.168.30.10
