version: '2.0'
services:

  frontend:
    image: frontend
    ports:
      - 5000:5000
    networks:
      - net

  backend:
    image: backend
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: annuaire
    networks:
      - net

  db:
    image: mysql:5.7
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: annuaire
    volumes:
      - ./data:/var/lib/mysql #cheminlocal:cheminconteneur

networks:
  net: