version: '2.4'
services:
  frontend:
    image: frontend
    ports:
      - 192.168.0.2:5000
    networks:
      vlan:
        ipv4_address: 192.168.0.2

  backend:
    image: backend
    ports:
      - 192.168.0.3:5001
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: annuaire
    networks:
      vlan:
        ipv4_address: 192.168.0.3


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: annuaire
    volumes:
      - ./data:/var/lib/mysql #cheminlocal:cheminconteneur
    networks:
      vlan:
        ipv4_address: 192.168.0.4

networks:
  dockervlan:
    name: frontend
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      config:
        - subnet: "192.168.20.0/24"
          gateway: "192.168.20.1"



