version: '2.4'
services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    networks:
      frontend-network:
        ipv4_address: 192.168.20.2
    restart: on-failure

  backend:
    image: backend
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: annuaire
    networks:
      backend-network:
        ipv4_address: 192.168.10.2
    restart: on-failure


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: annuaire
    volumes:
      - ./data:/var/lib/mysql #cheminlocal:cheminconteneur
    networks:
      db-network:
        ipv4_address: 192.168.30.2
    ports:
      - 3307:3306

networks:
  frontend-network:
    name: frontend-network
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      config:
        - subnet: "192.168.20.0/24"
          gateway: "192.168.20.1"

  backend-network:
    name: backend-network
    driver: macvlan
    driver_opts:
      parent: ens192
    ipam:
      config:
        - subnet: "192.168.10.0/24"
          gateway: "192.168.10.1"

  db-network:
    name: db-network
    driver: macvlan
    driver_opts:
      parent: ens256
    ipam:
      config:
        - subnet: "192.168.30.0/24"
          gateway: "192.168.30.1"

